# Generated by Django 4.0.2 on 2022-03-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro_hora_extra", "0003_registrohoraextra_horas"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrohoraextra",
            name="utilizada",
            field=models.BooleanField(default=False),
        ),
    ]
